name: DECODEJS
description: Trình giải nén JavaScript
version: 1.3.0
author: Ẩn danh
author_email: contact@laptrinhbanthan.com
url: https://decodejs.laptrinhbanthan.com
baseurl: /de4js
license: MIT

theme: jekyll-theme-hacker
show_downloads: false
google_analytics: UA-123121912-5
sass:
  style: compressed

exclude: ['Gemfile', 'Gemfile.lock', 'node_modules', 'package.json', 'package-lock.json']
